name : CoDF
train:
  seed : 3407
  device : cuda:0
  num_workers : 16
  batch_size : 32
  epochs : 100
  dropout : 0.1
  save_dir : /home/data/hsb/checkpoint/LULC/
  
optimizer :
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-2


scheduler : 
  _target_ : torch.optim.lr_scheduler.CosineAnnealingLR
  T_max : ${model.train.epochs}


use_model : 
  _target_ : model.CoDF.top.CoDF
  drop : ${model.train.dropout}
  in_dim1 : ${dataset.hsi_channel}
  in_dim2 : ${dataset.lidar_channel}
  out_dim : ${dataset.num_classes}
  layers : [2,6,2]
  embed_dim : [64,128,256]
  hidden_dim : 128
