name : CoDF
training_settings :
  seed : 3407
  device : cuda:0
  num_workers : 16
  train_batch_size : 32
  test_batch_size : 32
  epochs : 100
  early_stop : 1000
  dropout : 0.1
  checkpoint : /home/data/hsb/checkpoint/CoDF.pt

optimizer :
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-2


scheduler : 
  _target_ : torch.optim.lr_scheduler.CosineAnnealingLR
  T_max : ${model.training_settings.epochs}


use_model : 
  _target_ : model.CoDF.top.CoDF
  drop : ${model.training_settings.dropout}
  in_dim1 : ${dataset.hsi_channel}
  in_dim2 : ${dataset.lidar_channel}
  out_dim : ${dataset.num_classes}
  layers : [2,6,2]
  embed_dim : [64,128,256]
  hidden_dim : 128
